spring.application.name=lab2-chinook-api
spring.datasource.url=jdbc:postgresql://localhost:4210/chinook
spring.datasource.username=postgres
spring.datasource.password=${DB_PASSWORD}

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false
spring.jpa.show-sql=true