package edu.gcu.cst339.lab2_chinook_api.album;

import java.net.URI;
import java.util.List;

import org.springframework.dao.DataIntegrityViolationException;
import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.DeleteMapping;
import org.springframework.web.bind.annotation.ExceptionHandler;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.PutMapping;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.ResponseStatus;
import org.springframework.web.bind.annotation.RestController;
import org.springframework.web.servlet.support.ServletUriComponentsBuilder;

import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.responses.ApiResponse;
import io.swagger.v3.oas.annotations.tags.Tag;
import jakarta.validation.Valid;

/**
 * REST API for CRUD operations on Chinook Albums
 * AlbumController
 */
@Tag(name = "Albums", description = "CRUD operations for Chinook albums")
@RestController
@RequestMapping("/api/albums")
class AlbumController {
    
    private final AlbumService albumService;

    AlbumController(AlbumService albumService) {
        this.albumService = albumService;
    }

    /**
     * Returns all albums.
     *
     * @return list of all albums
     */
    @Operation(summary = "Get all albums")
    @ApiResponse(responseCode = "200", description = "List of all albums")
    @GetMapping
    List<AlbumDto> getAll() {
        return albumService.findAll();
    }

    /**
     * Returns a single album by its ID.
     *
     * @param id the ID of the album
     * @return the album with the specified ID
     * @throws AlbumNotFoundException if the album with the specified ID does not exist
     */
    @Operation(summary = "Get an album by ID")
    @ApiResponse(responseCode = "200", description = "Album found")
    @ApiResponse(responseCode = "404", description = "No album with that ID")
    @GetMapping("/{id}")
    AlbumDto getById(@PathVariable Integer id) {
        return albumService.findById(id);
    }
    
    /**
     * Creates a new album.
     *
     * @param dto the album data to create
     * @return the created album
     */
    @Operation(summary = "Create an album", description = "The albumId is generated by the database; omit it from the request.")
    @ApiResponse(responseCode = "201", description = "Album created")
    @ApiResponse(responseCode = "400", description = "Invalid album data")
    @ApiResponse(responseCode = "409", description = "artistId does not exist")
    @PostMapping
    ResponseEntity<AlbumDto> create(@RequestBody @Valid AlbumDto dto) {
        AlbumDto createdAlbum = albumService.create(dto);
        URI location = ServletUriComponentsBuilder.fromCurrentRequest()
            .path("/{id}")
            .buildAndExpand(createdAlbum.albumId())
            .toUri();
        return ResponseEntity.created(location).body(createdAlbum);
    }

    /**
     * Updates a single album by its ID.
     *
     * @param id the ID of the album to update
     * @param dto the album data to update
     * @return the updated album
     * @throws AlbumNotFoundException if the album with the specified ID does not exist
     */
    @Operation(summary = "Update an album", description = "The ID comes from the URL; any albumId in the body is ignored.")
    @ApiResponse(responseCode = "200", description = "Album updated")
    @ApiResponse(responseCode = "400", description = "Invalid album data")
    @ApiResponse(responseCode = "404", description = "No album with that ID")
    @ApiResponse(responseCode = "409", description = "artistId does not exist")
    @PutMapping("/{id}")
    ResponseEntity<AlbumDto> update(@PathVariable Integer id, @RequestBody @Valid AlbumDto dto) {
        AlbumDto updatedAlbum = albumService.update(id, dto);
        return ResponseEntity.ok(updatedAlbum);
    }

    /**
     * Deletes a single album by its ID.
     *
     * @param id the ID of the album to delete
     * @throws AlbumNotFoundException if the album with the specified ID does not exist
     */
    @Operation(summary = "Delete an album")
    @ApiResponse(responseCode = "204", description = "Album deleted")
    @ApiResponse(responseCode = "404", description = "No album with that ID")
    @ApiResponse(responseCode = "409", description = "Album still has tracks")
    @DeleteMapping("/{id}")
    @ResponseStatus(HttpStatus.NO_CONTENT)
    void delete(@PathVariable Integer id) {
        albumService.delete(id);
    }

    /**
     * Converts database constraint violations into HTTP 409 Conflict responses.
     */
    @ExceptionHandler(DataIntegrityViolationException.class)
    ResponseEntity<String> handleConflict(DataIntegrityViolationException ex) {
        return ResponseEntity.status(HttpStatus.CONFLICT)
            .body("Request conflicts with existing data (foreign key constraint).");
    }
}
